### ISSUE TITLE
Items teleporting to other sorting systems despite distance being longer than specified config.json distance

### ISSUE THREAD

**Issue by nathandstory** [jhuckaby/magic-sorting-system#13]
Im not sure if this is incompatible with 1.14.4, but I have a server with a few friends, all our houses are more than 50 blocks apart but less than 100, so i changed the max teleport distance to 24 blocks hoping it would fix it, but for some reason items are still teleporting over 50 blocks away to my friends sorting setup. I've tried a fresh install of the data pack as well as removing their gold block/lapis block setup that I helped them setup(thinking maybe it had to do with my player UUID somehow). Not really sure what to do. Is the 128 block teleport distance hardcoded in in any way outside the config? Any help would be appreciated, thanks.

**Comment by nathandstory** [comment]
Ive noticed that the majority of items go into my chest if they have a category setup for them, but anything that does not have a category skips my miscellaneous chest and goes right to someone else's categorized chest over 100 blocks away.

**Comment by jhuckaby** [comment]
Hi there!  And thanks for using the data pack.  Changing the max teleport distance requires that you **recompile** the pack from the source code, and basically generate a new pack.  To do this, you will need to install [Node.js](https://nodejs.org/) on your PC.  The instructions are here:

https://github.com/jhuckaby/magic-sorting-system#compiling

Good luck!

**Comment by nathandstory** [comment]
Ahh okay, I probably should have looked through the documentation a little better. I am familiar with node.js and I will try that! Thankyou for the help.

Edit: It worked! Thanks again.
