### ISSUE TITLE
Iron blocks not in a category

### ISSUE THREAD

**Issue by polyjitter** [jhuckaby/magic-sorting-system#14]
Iron blocks don't have a category, which is somewhat odd. Feel like they belong in "Precious".

**Comment by jhuckaby** [comment]
Are you sure?  They're registered in the [Tools](https://github.com/jhuckaby/magic-sorting-system#tools) group.  Source:

https://github.com/jhuckaby/magic-sorting-system/blob/master/source/config.json#L333

Just tested, and it works as designed.  Are you sure you have a proper tools category setup, with a wooden pickaxe in the item frame?
