### ISSUE TITLE
Group item cant be empty

### ISSUE THREAD

**Issue by thegamerx1** [jhuckaby/magic-sorting-system#19]
If you leave any group items empty the datapack wont work and will throw and error on compile. But adding `random:random` fixes it i would like that adding `random:random` to not be necesary for this

> Error
```
            "items": []
```
> OK
```
            "items": [
                "notminecraft:empty"
            ]
```

**Comment by jhuckaby** [comment]
I'm sorry, but you cannot have any empty groups, especially not the misc catch-all group.  Doing so may cause the datapack to malfunction.

You can remove any groups you don't like, but the final "misc" group is required, as it serves as the universal fallback.

If you don't want a universal fallback for some reason, and would prefer that overflow items teleport back to you (the nearest player), then simply do not craft a carrot-on-a-stick item frame.

**Comment by thegamerx1** [comment]
i want the misc group but i dont want having the carrot on a stick teleporting to the misc chest as of i prefer it in the tools chest but just adding a random id its fine. Having the items array empty makes it look clearer
