### ISSUE TITLE
Lapis Blocks

### ISSUE THREAD

**Issue by Xinoehp** [jhuckaby/magic-sorting-system#2]
I'm not 100% sure if this has been set up correctly (I didn't set it up) but we've got this installed on Realms and there's a nearby build that uses lapis blocks and the items to be sorted, once the chest has been broken, end up on these lapis blocks. Is there a problem with my set up (I've got a carrot stick hopper set up and a dirt hopper set up and I've managed to get some dirt to teleport once) or is the other lapis an issue?

**Comment by jhuckaby** [comment]
The other lapis blocks should not be an issue, but it sounds like you need to build walls around your drop-off chest.  Minecraft tends to "toss about" the items when you destroy the chest, meaning they fly around to nearby blocks.  So you need to build walls to contain the items, so they fall **exactly** on the center lapis block.  This lapis block also *must have a gold block underneath it*, in order to activate the teleportation.

Instructions here: https://github.com/jhuckaby/magic-sorting-system#creating-the-controller

**Comment by Xinoehp** [comment]
The other lapis blocks though are in a completely different room quite far
away and yet when I was trying to get some dirt to teleport to a dirt
hopper, it teleported to these lapis blocks far away in a completely
different room. As for the controller, I have made this design
<https://camo.githubusercontent.com/90997974be5e4061d7e977129613e3826828827e/68747470733a2f2f7069786c636f72652e636f6d2f736f6674776172652f6d73732f73637265656e73686f74732f616c742d636f6e74726f6c6c65722d322e706e67>
with
more lapis and gold to eliminate the need for more glass. I will try to use
a design surrounded by walls though and see if that helps.

**Comment by jhuckaby** [comment]
That is really bizarre.  I've never seen that behavior before.  The teleport command explicitly moves the items to the nearest item frame (which is an entity, not a block) with the correct group item displayed.  It has no ability or code to teleport items to a random block.

The only things I can suggest are to build walls around the chest (which you are trying) and also make sure your item frames have some empty air blocks around them.  Sometimes when teleporting items to item frames that are "cramped" the items end up in the wrong place.  This is especially true if you are trying to teleport more than 5 items (which fills up the hopper).  Another thing you can do is craft multiple hoppers with multiple matching item frames, and the system will load balance between them.

See this issue for more details on this problem, and suggested solutions: https://github.com/jhuckaby/magic-sorting-system/issues/1

**Comment by Xinoehp** [comment]
Issue solved, sorry! I was being so stupid. I assumed the pack teleported the items into the hoppers themselves. The other room had item frames in them. Thanks for your help and I'm sorry for wasting your time!

**Comment by jhuckaby** [comment]
No worries, glad you were able to figure it out!
