### ISSUE TITLE
Books not being teleported

### ISSUE THREAD

**Issue by thegamerx1** [jhuckaby/magic-sorting-system#20]
My books are not being teleported for some reason
https://youtu.be/aXjuVyQEPpY

> Config.json
https://pastebin.com/9gATHT3i

**Comment by jhuckaby** [comment]
I'm so sorry, but I cannot reproduce this issue.  I tried your exact config file as well:

https://www.youtube.com/watch?v=TlXH3Wk-RxI&feature=youtu.be

Something must be different with your PC or your Minecraft version or configuration.

Sorry!

**Comment by thegamerx1** [comment]
FOUND THE PROBLEM it was because in the fuctions folder the function file was `sort_Books.mcfunction` which should have been `sort_books.mcfunction`
and removing the file and recompiling fixed it!!!!! The problem happend because the compiler probably didnt check for caps or didnt detected the group name and the file name was different

The cap happend because i first compiled the config with the group having a cap in the B but then i removed it to match the other groups
