### ISSUE TITLE
1.16

### ISSUE THREAD

**Issue by TrinTragula** [jhuckaby/magic-sorting-system#29]
Are there any plans to update for 1.16? Not to rush you or anything, I just wanna know if I'll have to update the config myself :)

**Comment by jhuckaby** [comment]
Yup, I am totally planning to do this.  I was just waiting for the various Minecraft Wiki websites to update with all the new 1.16 Item IDs, so I could get a definitive list, and not have to dig through the game 😊

**Comment by jhuckaby** [comment]
[v2.0.2](https://github.com/jhuckaby/magic-sorting-system/releases/tag/v2.0.2) has just been released with all the 1.16 items 😊
