### ISSUE TITLE
Not working 1.13.1

### ISSUE THREAD

**Issue by F3LIXIS** [jhuckaby/magic-sorting-system#3]
![image](https://user-images.githubusercontent.com/44908591/48285051-2bcbf380-e416-11e8-9768-b5be226a5ee0.png)

Does not work on my 1.13.1 server, wondering if I'm doing something or if it hasn't been updated to work? Thanks! Looks like a great addition to the server if it works! I do not get the "Magic Sorting Chest is ready to use" in game, and even when setting up the controller and receiver it does not function.

**Comment by F3LIXIS** [comment]
I instead installed using a folder instead of .zip. That fixed it for some reason!

**Comment by jhuckaby** [comment]
Yeah sorry about that, for some reason Minecraft rejects the ZIP files that GitHub automatically generates from releases.  I wish I knew why.
