### ISSUE TITLE
Unable to send further than 128 blocks

### ISSUE THREAD

**Issue by camarokris** [jhuckaby/magic-sorting-system#31]
Per instruction I have increased the "max_teleport_distance" in the config.json to more than 128 (tested 1000, 500, 250) and have the receiving chests at the world spawn point, however this did not work. 

Looking at the mcfunction files in data/mss/functions this may be due to the range being hardcoded 0..128

Not sure if that is the reason as I have not personally done any coding for MC but its the only other reference to 128 in the form of distance that I have found in the files. Is there a way to replace the 0..128 with a 0..{variable} so it grabs the "max_teleport_distance" from the config?

**Comment by jhuckaby** [comment]
If you make any changes to the config file, you need to "recompile" all the functions.  Instructions here:

https://github.com/jhuckaby/magic-sorting-system#compiling
