### ISSUE TITLE
New 1.14 items

### ISSUE THREAD

**Issue by TrinTragula** [jhuckaby/magic-sorting-system#7]
Are you planning on implementing the new items coming in the 1.14 release in the datatpack?

**Comment by jhuckaby** [comment]
Absolutely!  I was just waiting for the item list to be finalized, and for the various Wikis to be updated, so I can be sure to get the Item IDs correct.

**Comment by TrinTragula** [comment]
Thank you so much! If it helps, I'm actually using the datapack in the 1.14 pre-release and it works fine with all the old items, as you might expect.

**Comment by groovy-d** [comment]
Thanks I was just about to try to put them in myself  :)  I'm making a new group file so I can sort the way I want stuff seperated out.  Never did this before, so fun fun

**Comment by jhuckaby** [comment]
Okay, all 1.14 blocks and items added!  Should be good to go. v1.0.1 released.

**Comment by groovy-d** [comment]
Cuz you rock :)
